/**
 * 华为云APM Mock数据
 * 从华为云APM接口获取的真实数据示例
 *
 * 支持两种格式：
 * 1. 旧格式：扁平的 span_event_list 数组（通过 id 字段的层级关系表示父子关系）
 * 2. 新格式：嵌套的 span_list 数组（通过 children 数组表示父子关系，使用 parent_spanId 字段）
 */

// 旧格式数据（保留用于兼容性）
export const HUAWEI_CLOUD_MOCK_TRACE = {
  "code": 0,
  "data": {
    "span_event_list": [
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "argument": "(GET)(/ocs/radioV2/radioSubscribeList?pageSize=500\u0026currentPage=1\u0026\u0026uid=269313\u0026phone=15357018793\u0026vin=LNNBBDFC5TD977150)(200)",
        "async": false,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 19,
        "class_name": "io/undertow/servlet/handlers/ServletInitialHandler",
        "code": 200,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1",
        "global_trace_id": "1146880-1774346359990-549606",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "http_method": "GET",
        "id": "1+1",
        "indent": 0,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": false,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "dispatchRequest",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "real_source": "/ocs/radioV2/radioSubscribeList?pageSize=500\u0026currentPage=1\u0026\u0026uid=269313\u0026phone=15357018793\u0026vin=LNNBBDFC5TD977150",
        "region": "cn-east-3",
        "source": "/ocs/radioV2/radioSubscribeList",
        "span_id": "1",
        "start_time": 1774346359990,
        "tags": {},
        "time_used": 104,
        "trace_id": "1146880-1774346359990-549606",
        "type": "Undertow"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "async": true,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "io/lettuce/core/protocol/BaseRedisCommandBuilder",
        "code": 0,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1-1",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "id": "1+1-1",
        "indent": 1,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": true,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "GET",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "region": "cn-east-3",
        "span_id": "1",
        "start_time": 1774346359991,
        "tags": {},
        "time_used": 0,
        "trace_id": "1146880-1774346359990-549606",
        "type": "REDIS_CLIENT"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "argument": "(GET)(https://api.ximalaya.com/iot/openapi-smart-device-api/radios/2192/playing-program?access_token=xxx)(200)",
        "async": false,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "okhttp3/internal/http/RealInterceptorChain",
        "code": 0,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1-14",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "http_method": "GET",
        "id": "1+1-14",
        "indent": 1,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": false,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "proceed",
        "next_spanId": "1-1",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "region": "cn-east-3",
        "real_source": "https://api.ximalaya.com",
        "span_id": "1",
        "start_time": 1774346360010,
        "tags": {},
        "time_used": 16,
        "trace_id": "1146880-1774346359990-549606",
        "type": "Okhttpclient"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "async": false,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "com/mysql/cj/jdbc/ClientPreparedStatement",
        "code": 0,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1-8",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "id": "1+1-8",
        "indent": 1,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": false,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "execute",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "region": "cn-east-3",
        "span_id": "1",
        "start_time": 1774346360000,
        "tags": {},
        "time_used": 1,
        "trace_id": "1146880-1774346359990-549606",
        "type": "Mysql"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "argument": "java.util.concurrent.CompletableFuture$AsyncRun",
        "async": false,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 3,
        "class_name": "java/util/concurrent/ThreadPoolExecutor",
        "code": 200,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1",
        "global_trace_id": "1146880-1774346359990-549606",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "id": "1-3+1",
        "indent": 2,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": false,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "run",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "real_source": "run()",
        "region": "cn-east-3",
        "source": "run()",
        "span_id": "1-3",
        "start_time": 1774346360040,
        "tags": {},
        "time_used": 17,
        "trace_id": "1146880-1774346359990-549606",
        "type": "ASYNC_THREAD"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "async": true,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "io/lettuce/core/protocol/BaseRedisCommandBuilder",
        "code": 0,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1-1",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "id": "1-3+1-1",
        "indent": 3,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": true,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "GET",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "region": "cn-east-3",
        "span_id": "1-3",
        "start_time": 1774346360040,
        "tags": {},
        "time_used": 0,
        "trace_id": "1146880-1774346359990-549606",
        "type": "REDIS_CLIENT"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "async": true,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "io/lettuce/core/protocol/BaseRedisCommandBuilder",
        "code": 0,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1-2",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "id": "1-3+1-2",
        "indent": 3,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": true,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "GET",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "region": "cn-east-3",
        "span_id": "1-3",
        "start_time": 1774346360041,
        "tags": {},
        "time_used": 0,
        "trace_id": "1146880-1774346359990-549606",
        "type": "REDIS_CLIENT"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "argument": "(GET)(https://api.ximalaya.com/iot/openapi-smart-device-api/radios/2192?access_token=xxx)(200)",
        "async": false,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "okhttp3/internal/http/RealInterceptorChain",
        "code": 0,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1-3",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "http_method": "GET",
        "id": "1-3+1-3",
        "indent": 3,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": false,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "proceed",
        "next_spanId": "1-3-1",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "region": "cn-east-3",
        "real_source": "https://api.ximalaya.com",
        "span_id": "1-3",
        "start_time": 1774346360042,
        "tags": {},
        "time_used": 15,
        "trace_id": "1146880-1774346359990-549606",
        "type": "Okhttpclient"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "async": false,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "java/util/concurrent/ThreadPoolExecutor",
        "code": 200,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1",
        "global_trace_id": "1146880-1774346359990-549606",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "id": "1-4+1",
        "indent": 2,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": false,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "run",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "real_source": "run()",
        "region": "cn-east-3",
        "source": "run()",
        "span_id": "1-4",
        "start_time": 1774346360040,
        "tags": {},
        "time_used": 53,
        "trace_id": "1146880-1774346359990-549606",
        "type": "ASYNC_THREAD"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "async": true,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "io/lettuce/core/protocol/BaseRedisCommandBuilder",
        "code": 0,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1-1",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "id": "1-4+1-1",
        "indent": 3,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": true,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "GET",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "region": "cn-east-3",
        "span_id": "1-4",
        "start_time": 1774346360040,
        "tags": {},
        "time_used": 0,
        "trace_id": "1146880-1774346359990-549606",
        "type": "REDIS_CLIENT"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "async": true,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "io/lettuce/core/protocol/BaseRedisCommandBuilder",
        "code": 0,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1-2",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "id": "1-4+1-2",
        "indent": 3,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": true,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c2615dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "GET",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "region": "cn-east-3",
        "span_id": "1-4",
        "start_time": 1774346360041,
        "tags": {},
        "time_used": 0,
        "trace_id": "1146880-1774346359990-549606",
        "type": "REDIS_CLIENT"
      },
      {
        "app_id": 3321250,
        "app_name": "csc-outer-cpsp-service",
        "app_type": "JAVA",
        "argument": "(GET)(https://api.ximalaya.com/iot/openapi-smart-device-api/radios/1011?access_token=xxx)(200)",
        "async": false,
        "biz_id": 6326738,
        "biz_name": "lioncloud",
        "children_event_count": 0,
        "class_name": "okhttp3/internal/http/RealInterceptorChain",
        "code": 0,
        "discard": [],
        "display_name": "lioncloud",
        "domain_id": 8132,
        "env_id": 2290213,
        "env_name": "prod",
        "event_id": "1-3",
        "has_error": false,
        "host_name": "csc-outer-cpsp-service-685696778d-4tfdj",
        "http_method": "GET",
        "id": "1-4+1-3",
        "indent": 3,
        "instance_id": 1146880,
        "instance_name": "default",
        "ip_address": "172.25.173.150",
        "is_async": false,
        "log_group_id": "05bd04bf-d7d1-4653-a270-816d2c261dc",
        "log_stream_id": "fc2f233b-38f3-4f5c-9894-fd5ec8ab864d",
        "method": "proceed",
        "next_spanId": "1-4-1",
        "print_trace_id_flag": true,
        "project_id": "a0970e7178fc45d99ecd263989f56257",
        "region": "cn-east-3",
        "real_source": "https://api.ximalaya.com",
        "span_id": "1-4",
        "start_time": 1774346360042,
        "tags": {},
        "time_used": 51,
        "trace_id": "1146880-1774346359990-549606",
        "type": "Okhttpclient"
      }
    ]
  },
  "msg": "ok"
};

// 新格式数据示例（嵌套 children 数组格式）
export const HUAWEI_CLOUD_MOCK_TRACE_V2 = {
  "code": 0,
  "data": {
    "span_list": [
        {
            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
            "span_id": "6cff08dfa5de9c8b",
            "parent_spanId": "",
            "start_time": 1774505651776,
            "operation_name": "user.action.RestTemplate",
            "span_type": "SPAN_KIND_INTERNAL",
            "tags": {
                "baggage.userId": "user-001",
                "otel.scope.name": "tsp-react-frontend",
                "baggage.platform": "h5",
                "baggage.tenantId": "tsp-prod",
                "baggage.vin": "VIN-REACT-001",
                "otel.scope.version": "1.0.0",
                "ui.scenario": "RestTemplate"
            },
            "inner_domain_id": 10936,
            "biz_id": 6611906,
            "app_id": 3335515,
            "env_id": 2311244,
            "instance_id": 99835,
            "time_used": 199,
            "env_name": "test",
            "instance_name": "undef-hostname@undef-instancename@undef-ip",
            "app_name": "tsp-react-frontend",
            "region": "cn-east-3",
            "host_name": "undef-hostname",
            "ip_address": "undef-ip",
            "print_trace_id_flag": false,
            "app_type": "UNKNOWN",
            "children": [
                {
                    "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                    "span_id": "83f49282d89796cb",
                    "parent_spanId": "6cff08dfa5de9c8b",
                    "start_time": 1774505651776,
                    "operation_name": "POST http://localhost:3000/biz/rest/command",
                    "span_type": "SPAN_KIND_CLIENT",
                    "tags": {
                        "otel.scope.name": "@opentelemetry/instrumentation-fetch",
                        "baggage.platform": "h5",
                        "http.url": "http://localhost:3000/biz/rest/command",
                        "baggage.vin": "VIN-REACT-001",
                        "otel.scope.version": "0.53.0",
                        "http.host": "localhost:3000",
                        "http.status_code": "200",
                        "component": "fetch",
                        "baggage.userId": "user-001",
                        "http.response_content_length": "1370",
                        "http.user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36",
                        "baggage.tenantId": "tsp-prod",
                        "http.status_text": "OK",
                        "http.method": "POST",
                        "http.scheme": "http"
                    },
                    "inner_domain_id": 10936,
                    "biz_id": 6611906,
                    "app_id": 3335515,
                    "env_id": 2311244,
                    "instance_id": 99835,
                    "time_used": 200,
                    "env_name": "test",
                    "instance_name": "undef-hostname@undef-instancename@undef-ip",
                    "app_name": "tsp-react-frontend",
                    "region": "cn-east-3",
                    "host_name": "undef-hostname",
                    "ip_address": "undef-ip",
                    "print_trace_id_flag": false,
                    "app_type": "UNKNOWN",
                    "children": [
                        {
                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                            "span_id": "c324814fa27ac82d",
                            "parent_spanId": "83f49282d89796cb",
                            "start_time": 1774505652056,
                            "operation_name": "kong",
                            "span_type": "SPAN_KIND_SERVER",
                            "tags": {
                                "http.status_code": "200",
                                "otel.scope.name": "kong-internal",
                                "http.flavor": "1.1",
                                "http.route": "/biz",
                                "kong.request.id": "d50de76409bc054d39fc1042661bdc27",
                                "http.url": "http://106.14.92.45/biz/rest/command",
                                "otel.scope.version": "0.1.0",
                                "net.peer.ip": "140.207.36.34",
                                "http.method": "POST",
                                "http.host": "106.14.92.45",
                                "http.scheme": "http",
                                "http.client_ip": "140.207.36.34"
                            },
                            "inner_domain_id": 10936,
                            "biz_id": 6611906,
                            "app_id": 3335517,
                            "env_id": 2311248,
                            "instance_id": 99853,
                            "time_used": 150,
                            "env_name": "test",
                            "instance_name": "undef-hostname@undef-instancename@undef-ip(3f572eb7-8ab2-4847-85de-bcece5779b31)",
                            "app_name": "kong",
                            "region": "cn-east-3",
                            "host_name": "undef-hostname",
                            "ip_address": "undef-ip",
                            "print_trace_id_flag": false,
                            "app_type": "UNKNOWN",
                            "children": [
                                {
                                    "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                    "span_id": "0fdae5ee229c0c77",
                                    "parent_spanId": "c324814fa27ac82d",
                                    "start_time": 1774505652058,
                                    "operation_name": "kong.balancer",
                                    "span_type": "SPAN_KIND_CLIENT",
                                    "tags": {
                                        "net.peer.name": "172.19.64.30",
                                        "otel.scope.name": "kong-internal",
                                        "net.peer.port": "8091.0",
                                        "try_count": "1.0",
                                        "otel.scope.version": "0.1.0",
                                        "net.peer.ip": "172.19.64.30"
                                    },
                                    "inner_domain_id": 10936,
                                    "biz_id": 6611906,
                                    "app_id": 3335517,
                                    "env_id": 2311248,
                                    "instance_id": 99853,
                                    "time_used": 148,
                                    "env_name": "test",
                                    "instance_name": "undef-hostname@undef-instancename@undef-ip(3f572eb7-8ab2-4847-85de-bcece5779b31)",
                                    "app_name": "kong",
                                    "region": "cn-east-3",
                                    "host_name": "undef-hostname",
                                    "ip_address": "undef-ip",
                                    "print_trace_id_flag": false,
                                    "app_type": "UNKNOWN",
                                    "children": [
                                        {
                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                            "span_id": "644334f77866dc01",
                                            "parent_spanId": "0fdae5ee229c0c77",
                                            "start_time": 1774505652059,
                                            "operation_name": "POST /biz/rest/command",
                                            "span_type": "SPAN_KIND_SERVER",
                                            "tags": {
                                                "user_agent.original": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36",
                                                "otel.scope.name": "io.opentelemetry.tomcat-7.0",
                                                "baggage.platform": "h5",
                                                "network.protocol.version": "1.1",
                                                "network.peer.port": "47984",
                                                "baggage.vin": "VIN-REACT-001",
                                                "otel.scope.version": "2.25.0-alpha",
                                                "url.scheme": "http",
                                                "thread.name": "http-nio-8091-exec-10",
                                                "userId": "user-001",
                                                "platform": "h5",
                                                "server.address": "106.14.92.45",
                                                "client.address": "140.207.36.34",
                                                "network.peer.address": "192.168.112.3",
                                                "url.path": "/biz/rest/command",
                                                "baggage.userId": "user-001",
                                                "http.request.method": "POST",
                                                "http.route": "/biz/rest/command",
                                                "baggage.tenantId": "tsp-prod",
                                                "tenantId": "tsp-prod",
                                                "vin": "VIN-REACT-001",
                                                "http.request.header.baggage": "values {  string_value: 'userId=user-001,vin=VIN-REACT-001,tenantId=tsp-prod,platform=h5'}",
                                                "http.response.status_code": "200",
                                                "thread.id": "38",
                                                "http.method": "POST",
                                                "http.target": "/biz/rest/command",
                                                "http.status_code": "200"
                                            },
                                            "inner_domain_id": 10936,
                                            "biz_id": 6611906,
                                            "app_id": 3335513,
                                            "env_id": 2311242,
                                            "instance_id": 99804,
                                            "time_used": 147,
                                            "env_name": "test",
                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                            "app_name": "tsp-trace-service1",
                                            "region": "cn-east-3",
                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                            "ip_address": "undef-ip",
                                            "print_trace_id_flag": false,
                                            "app_type": "JAVA",
                                            "children": [
                                                {
                                                    "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                    "span_id": "09baf8a0bb37660e",
                                                    "parent_spanId": "644334f77866dc01",
                                                    "start_time": 1774505652062,
                                                    "operation_name": "biz.call.rest",
                                                    "span_type": "SPAN_KIND_CLIENT",
                                                    "tags": {
                                                        "otel.scope.name": "tsp-service1",
                                                        "baggage.platform": "h5",
                                                        "baggage.vin": "VIN-REACT-001",
                                                        "thread.name": "http-nio-8091-exec-10",
                                                        "tsp.call.type": "RestTemplate",
                                                        "userId": "user-001",
                                                        "platform": "h5",
                                                        "tsp.vin": "VIN-REACT-001",
                                                        "baggage.userId": "user-001",
                                                        "baggage.tenantId": "tsp-prod",
                                                        "tenantId": "tsp-prod",
                                                        "vin": "VIN-REACT-001",
                                                        "thread.id": "38"
                                                    },
                                                    "inner_domain_id": 10936,
                                                    "biz_id": 6611906,
                                                    "app_id": 3335513,
                                                    "env_id": 2311242,
                                                    "instance_id": 99804,
                                                    "time_used": 142,
                                                    "env_name": "test",
                                                    "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                    "app_name": "tsp-trace-service1",
                                                    "region": "cn-east-3",
                                                    "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                    "ip_address": "undef-ip",
                                                    "print_trace_id_flag": false,
                                                    "app_type": "JAVA",
                                                    "children": [
                                                        {
                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                            "span_id": "ce32c5aab4dde75a",
                                                            "parent_spanId": "09baf8a0bb37660e",
                                                            "start_time": 1774505652063,
                                                            "operation_name": "GET tsp:vin:VIN-REACT-001",
                                                            "span_type": "SPAN_KIND_CLIENT",
                                                            "tags": {
                                                                "otel.scope.name": "io.opentelemetry.lettuce-5.1",
                                                                "db.statement": "GET tsp:vin:VIN-REACT-001",
                                                                "baggage.platform": "h5",
                                                                "network.peer.port": "6379",
                                                                "baggage.vin": "VIN-REACT-001",
                                                                "otel.scope.version": "2.25.0-alpha",
                                                                "thread.name": "lettuce-nioEventLoop-4-1",
                                                                "userId": "user-001",
                                                                "platform": "h5",
                                                                "server.address": "172.19.64.30",
                                                                "network.peer.address": "172.19.64.30",
                                                                "baggage.userId": "user-001",
                                                                "db.system": "redis",
                                                                "peer.service": "Redis",
                                                                "baggage.tenantId": "tsp-prod",
                                                                "tenantId": "tsp-prod",
                                                                "server.port": "6379",
                                                                "vin": "VIN-REACT-001",
                                                                "network.type": "ipv4",
                                                                "thread.id": "42",
                                                                "db.connection_string": "redis://172.19.64.30:6379"
                                                            },
                                                            "inner_domain_id": 10936,
                                                            "biz_id": 6611906,
                                                            "app_id": 3335513,
                                                            "env_id": 2311242,
                                                            "instance_id": 99804,
                                                            "time_used": 1,
                                                            "env_name": "test",
                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                            "app_name": "tsp-trace-service1",
                                                            "region": "cn-east-3",
                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                            "ip_address": "undef-ip",
                                                            "print_trace_id_flag": false,
                                                            "app_type": "JAVA"
                                                        },
                                                        {
                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                            "span_id": "9cd3555937ddbef6",
                                                            "parent_spanId": "09baf8a0bb37660e",
                                                            "start_time": 1774505652066,
                                                            "operation_name": "SETEX tsp:vin:VIN-REACT-001 600 ?",
                                                            "span_type": "SPAN_KIND_CLIENT",
                                                            "tags": {
                                                                "otel.scope.name": "io.opentelemetry.lettuce-5.1",
                                                                "db.statement": "SETEX tsp:vin:VIN-REACT-001 600 ?",
                                                                "baggage.platform": "h5",
                                                                "network.peer.port": "6379",
                                                                "baggage.vin": "VIN-REACT-001",
                                                                "otel.scope.version": "2.25.0-alpha",
                                                                "thread.name": "lettuce-nioEventLoop-4-1",
                                                                "userId": "user-001",
                                                                "platform": "h5",
                                                                "server.address": "172.19.64.30",
                                                                "network.peer.address": "172.19.64.30",
                                                                "baggage.userId": "user-001",
                                                                "db.system": "redis",
                                                                "peer.service": "Redis",
                                                                "baggage.tenantId": "tsp-prod",
                                                                "tenantId": "tsp-prod",
                                                                "server.port": "6379",
                                                                "vin": "VIN-REACT-001",
                                                                "network.type": "ipv4",
                                                                "thread.id": "42",
                                                                "db.connection_string": "redis://172.19.64.30:6379"
                                                            },
                                                            "inner_domain_id": 10936,
                                                            "biz_id": 6611906,
                                                            "app_id": 3335513,
                                                            "env_id": 2311242,
                                                            "instance_id": 99804,
                                                            "time_used": 1,
                                                            "env_name": "test",
                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                            "app_name": "tsp-trace-service1",
                                                            "region": "cn-east-3",
                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                            "ip_address": "undef-ip",
                                                            "print_trace_id_flag": false,
                                                            "app_type": "JAVA"
                                                        },
                                                        {
                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                            "span_id": "cfc21ee5a71d1795",
                                                            "parent_spanId": "09baf8a0bb37660e",
                                                            "start_time": 1774505652067,
                                                            "operation_name": "CommandRecordRepository.save",
                                                            "span_type": "SPAN_KIND_INTERNAL",
                                                            "tags": {
                                                                "otel.scope.name": "io.opentelemetry.spring-data-1.8",
                                                                "code.function": "save",
                                                                "baggage.platform": "h5",
                                                                "baggage.vin": "VIN-REACT-001",
                                                                "otel.scope.version": "2.25.0-alpha",
                                                                "thread.name": "http-nio-8091-exec-10",
                                                                "userId": "user-001",
                                                                "platform": "h5",
                                                                "code.namespace": "com.tsp.service1.repository.CommandRecordRepository",
                                                                "baggage.userId": "user-001",
                                                                "baggage.tenantId": "tsp-prod",
                                                                "tenantId": "tsp-prod",
                                                                "vin": "VIN-REACT-001",
                                                                "thread.id": "38"
                                                            },
                                                            "inner_domain_id": 10936,
                                                            "biz_id": 6611906,
                                                            "app_id": 3335513,
                                                            "env_id": 2311242,
                                                            "instance_id": 99804,
                                                            "time_used": 11,
                                                            "env_name": "test",
                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                            "app_name": "tsp-trace-service1",
                                                            "region": "cn-east-3",
                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                            "ip_address": "undef-ip",
                                                            "print_trace_id_flag": false,
                                                            "app_type": "JAVA",
                                                            "children": [
                                                                {
                                                                    "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                                    "span_id": "c94916a90920f0c1",
                                                                    "parent_spanId": "cfc21ee5a71d1795",
                                                                    "start_time": 1774505652069,
                                                                    "operation_name": "Session.persist com.tsp.service1.entity.CommandRecord",
                                                                    "span_type": "SPAN_KIND_INTERNAL",
                                                                    "tags": {
                                                                        "baggage.userId": "user-001",
                                                                        "otel.scope.name": "io.opentelemetry.hibernate-4.0",
                                                                        "baggage.platform": "h5",
                                                                        "baggage.tenantId": "tsp-prod",
                                                                        "tenantId": "tsp-prod",
                                                                        "vin": "VIN-REACT-001",
                                                                        "baggage.vin": "VIN-REACT-001",
                                                                        "otel.scope.version": "2.25.0-alpha",
                                                                        "thread.name": "http-nio-8091-exec-10",
                                                                        "userId": "user-001",
                                                                        "platform": "h5",
                                                                        "thread.id": "38"
                                                                    },
                                                                    "inner_domain_id": 10936,
                                                                    "biz_id": 6611906,
                                                                    "app_id": 3335513,
                                                                    "env_id": 2311242,
                                                                    "instance_id": 99804,
                                                                    "time_used": 2,
                                                                    "env_name": "test",
                                                                    "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                                    "app_name": "tsp-trace-service1",
                                                                    "region": "cn-east-3",
                                                                    "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                                    "ip_address": "undef-ip",
                                                                    "print_trace_id_flag": false,
                                                                    "app_type": "JAVA",
                                                                    "children": [
                                                                        {
                                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                                            "span_id": "8168d9630f23806c",
                                                                            "parent_spanId": "c94916a90920f0c1",
                                                                            "start_time": 1774505652070,
                                                                            "operation_name": "insert into s1_command_record (call_type, command_type, created_at, span_id, status, trace_id, vin) values (?, ?, ?, ?, ?, ?, ?)",
                                                                            "span_type": "SPAN_KIND_CLIENT",
                                                                            "tags": {
                                                                                "db.connection_string": "mysql://172.19.64.30:13306",
                                                                                "otel.scope.name": "io.opentelemetry.jdbc",
                                                                                "db.statement": "insert into s1_command_record (call_type, command_type, created_at, span_id, status, trace_id, vin) values (?, ?, ?, ?, ?, ?, ?)",
                                                                                "baggage.platform": "h5",
                                                                                "db.sql.table": "s1_command_record",
                                                                                "db.operation": "INSERT",
                                                                                "baggage.vin": "VIN-REACT-001",
                                                                                "otel.scope.version": "2.25.0-alpha",
                                                                                "thread.name": "http-nio-8091-exec-10",
                                                                                "userId": "user-001",
                                                                                "platform": "h5",
                                                                                "server.address": "172.19.64.30",
                                                                                "db.user": "chery-alert",
                                                                                "baggage.userId": "user-001",
                                                                                "db.system": "mysql",
                                                                                "peer.service": "MySQL",
                                                                                "baggage.tenantId": "tsp-prod",
                                                                                "tenantId": "tsp-prod",
                                                                                "server.port": "13306",
                                                                                "vin": "VIN-REACT-001",
                                                                                "db.name": "trace_demo",
                                                                                "thread.id": "38"
                                                                            },
                                                                            "inner_domain_id": 10936,
                                                                            "biz_id": 6611906,
                                                                            "app_id": 3335513,
                                                                            "env_id": 2311242,
                                                                            "instance_id": 99804,
                                                                            "time_used": 0,
                                                                            "env_name": "test",
                                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                                            "app_name": "tsp-trace-service1",
                                                                            "region": "cn-east-3",
                                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                                            "ip_address": "undef-ip",
                                                                            "print_trace_id_flag": false,
                                                                            "app_type": "JAVA"
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                                    "span_id": "4bb4c2b50086ca19",
                                                                    "parent_spanId": "cfc21ee5a71d1795",
                                                                    "start_time": 1774505652071,
                                                                    "operation_name": "Transaction.commit",
                                                                    "span_type": "SPAN_KIND_INTERNAL",
                                                                    "tags": {
                                                                        "baggage.userId": "user-001",
                                                                        "otel.scope.name": "io.opentelemetry.hibernate-4.0",
                                                                        "baggage.platform": "h5",
                                                                        "baggage.tenantId": "tsp-prod",
                                                                        "tenantId": "tsp-prod",
                                                                        "vin": "VIN-REACT-001",
                                                                        "baggage.vin": "VIN-REACT-001",
                                                                        "otel.scope.version": "2.25.0-alpha",
                                                                        "thread.name": "http-nio-8091-exec-10",
                                                                        "userId": "user-001",
                                                                        "platform": "h5",
                                                                        "thread.id": "38"
                                                                    },
                                                                    "inner_domain_id": 10936,
                                                                    "biz_id": 6611906,
                                                                    "app_id": 3335513,
                                                                    "env_id": 2311242,
                                                                    "instance_id": 99804,
                                                                    "time_used": 7,
                                                                    "env_name": "test",
                                                                    "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                                    "app_name": "tsp-trace-service1",
                                                                    "region": "cn-east-3",
                                                                    "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                                    "ip_address": "undef-ip",
                                                                    "print_trace_id_flag": false,
                                                                    "app_type": "JAVA"
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                            "span_id": "7b31e1650aac0185",
                                                            "parent_spanId": "09baf8a0bb37660e",
                                                            "start_time": 1774505652081,
                                                            "operation_name": "POST http://172.19.64.30:8092/core/command",
                                                            "span_type": "SPAN_KIND_CLIENT",
                                                            "tags": {
                                                                "otel.scope.name": "io.opentelemetry.http-url-connection",
                                                                "baggage.platform": "h5",
                                                                "network.protocol.version": "1.1",
                                                                "baggage.vin": "VIN-REACT-001",
                                                                "otel.scope.version": "2.25.0-alpha",
                                                                "thread.name": "http-nio-8091-exec-10",
                                                                "userId": "user-001",
                                                                "platform": "h5",
                                                                "server.address": "172.19.64.30",
                                                                "baggage.userId": "user-001",
                                                                "http.request.method": "POST",
                                                                "baggage.tenantId": "tsp-prod",
                                                                "server.port": "8092",
                                                                "tenantId": "tsp-prod",
                                                                "vin": "VIN-REACT-001",
                                                                "http.response.status_code": "200",
                                                                "url.full": "http://172.19.64.30:8092/core/command",
                                                                "thread.id": "38",
                                                                "http.method": "POST"
                                                            },
                                                            "inner_domain_id": 10936,
                                                            "biz_id": 6611906,
                                                            "app_id": 3335513,
                                                            "env_id": 2311242,
                                                            "instance_id": 99804,
                                                            "time_used": 107,
                                                            "env_name": "test",
                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                            "app_name": "tsp-trace-service1",
                                                            "region": "cn-east-3",
                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                            "ip_address": "undef-ip",
                                                            "print_trace_id_flag": false,
                                                            "app_type": "JAVA",
                                                            "children": [
                                                                {
                                                                    "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                                    "span_id": "b8731aa87e560a09",
                                                                    "parent_spanId": "7b31e1650aac0185",
                                                                    "start_time": 1774505652083,
                                                                    "operation_name": "POST /core/command",
                                                                    "span_type": "SPAN_KIND_SERVER",
                                                                    "tags": {
                                                                        "otel.scope.name": "io.opentelemetry.tomcat-7.0",
                                                                        "baggage.vin": "VIN-REACT-001",
                                                                        "url.scheme": "http",
                                                                        "thread.name": "http-nio-8092-exec-10",
                                                                        "platform": "h5",
                                                                        "server.address": "172.19.64.30",
                                                                        "client.address": "172.19.64.30",
                                                                        "network.peer.address": "172.19.64.30",
                                                                        "http.request.method": "POST",
                                                                        "server.port": "8092",
                                                                        "vin": "VIN-REACT-001",
                                                                        "http.request.header.baggage": "values {  string_value: 'platform=h5,tenantId=tsp-prod,userId=user-001,vin=VIN-REACT-001'}",
                                                                        "http.response.status_code": "200",
                                                                        "thread.id": "39",
                                                                        "user_agent.original": "Java/11.0.23",
                                                                        "baggage.platform": "h5",
                                                                        "network.protocol.version": "1.1",
                                                                        "network.peer.port": "60206",
                                                                        "otel.scope.version": "2.25.0-alpha",
                                                                        "userId": "user-001",
                                                                        "url.path": "/core/command",
                                                                        "baggage.userId": "user-001",
                                                                        "http.route": "/core/command",
                                                                        "baggage.tenantId": "tsp-prod",
                                                                        "tenantId": "tsp-prod",
                                                                        "http.method": "POST",
                                                                        "http.target": "/core/command",
                                                                        "http.status_code": "200"
                                                                    },
                                                                    "inner_domain_id": 10936,
                                                                    "biz_id": 6611906,
                                                                    "app_id": 3335514,
                                                                    "env_id": 2311243,
                                                                    "instance_id": 99818,
                                                                    "time_used": 105,
                                                                    "env_name": "test",
                                                                    "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(4a56b0fe-cbd4-478e-971f-9216cf6f005c)",
                                                                    "app_name": "tsp-trace-service2",
                                                                    "region": "cn-east-3",
                                                                    "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                                    "ip_address": "undef-ip",
                                                                    "print_trace_id_flag": false,
                                                                    "app_type": "JAVA",
                                                                    "children": [
                                                                        {
                                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                                            "span_id": "1715082dd35d23f7",
                                                                            "parent_spanId": "b8731aa87e560a09",
                                                                            "start_time": 1774505652086,
                                                                            "operation_name": "async.manual.cmd-manual",
                                                                            "span_type": "SPAN_KIND_INTERNAL",
                                                                            "tags": {
                                                                                "otel.scope.name": "tsp-service2",
                                                                                "baggage.platform": "h5",
                                                                                "task.name": "cmd-manual",
                                                                                "baggage.vin": "VIN-REACT-001",
                                                                                "thread.name": "ForkJoinPool.commonPool-worker-3",
                                                                                "userId": "user-001",
                                                                                "platform": "h5",
                                                                                "baggage.userId": "user-001",
                                                                                "async.type": "Manual-Context",
                                                                                "baggage.tenantId": "tsp-prod",
                                                                                "tenantId": "tsp-prod",
                                                                                "vin": "VIN-REACT-001",
                                                                                "thread.id": "45"
                                                                            },
                                                                            "inner_domain_id": 10936,
                                                                            "biz_id": 6611906,
                                                                            "app_id": 3335514,
                                                                            "env_id": 2311243,
                                                                            "instance_id": 99818,
                                                                            "time_used": 80,
                                                                            "env_name": "test",
                                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(4a56b0fe-cbd4-478e-971f-9216cf6f005c)",
                                                                            "app_name": "tsp-trace-service2",
                                                                            "region": "cn-east-3",
                                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                                            "ip_address": "undef-ip",
                                                                            "print_trace_id_flag": false,
                                                                            "app_type": "JAVA"
                                                                        },
                                                                        {
                                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                                            "span_id": "1e3922ea7514d134",
                                                                            "parent_spanId": "b8731aa87e560a09",
                                                                            "start_time": 1774505652086,
                                                                            "operation_name": "async.task.cmd-process",
                                                                            "span_type": "SPAN_KIND_INTERNAL",
                                                                            "tags": {
                                                                                "otel.scope.name": "tsp-service2",
                                                                                "baggage.platform": "h5",
                                                                                "task.name": "cmd-process",
                                                                                "baggage.vin": "VIN-REACT-001",
                                                                                "thread.name": "tsp-async-3",
                                                                                "userId": "user-001",
                                                                                "platform": "h5",
                                                                                "baggage.userId": "user-001",
                                                                                "async.type": "@Async",
                                                                                "baggage.tenantId": "tsp-prod",
                                                                                "tenantId": "tsp-prod",
                                                                                "vin": "VIN-REACT-001",
                                                                                "thread.id": "53"
                                                                            },
                                                                            "inner_domain_id": 10936,
                                                                            "biz_id": 6611906,
                                                                            "app_id": 3335514,
                                                                            "env_id": 2311243,
                                                                            "instance_id": 99818,
                                                                            "time_used": 100,
                                                                            "env_name": "test",
                                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(4a56b0fe-cbd4-478e-971f-9216cf6f005c)",
                                                                            "app_name": "tsp-trace-service2",
                                                                            "region": "cn-east-3",
                                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                                            "ip_address": "undef-ip",
                                                                            "print_trace_id_flag": false,
                                                                            "app_type": "JAVA"
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                            "span_id": "46d192dff90af8d4",
                                                            "parent_spanId": "09baf8a0bb37660e",
                                                            "start_time": 1774505652189,
                                                            "operation_name": "CommandRecordRepository.save",
                                                            "span_type": "SPAN_KIND_INTERNAL",
                                                            "tags": {
                                                                "otel.scope.name": "io.opentelemetry.spring-data-1.8",
                                                                "code.function": "save",
                                                                "baggage.platform": "h5",
                                                                "baggage.vin": "VIN-REACT-001",
                                                                "otel.scope.version": "2.25.0-alpha",
                                                                "thread.name": "http-nio-8091-exec-10",
                                                                "userId": "user-001",
                                                                "platform": "h5",
                                                                "code.namespace": "com.tsp.service1.repository.CommandRecordRepository",
                                                                "baggage.userId": "user-001",
                                                                "baggage.tenantId": "tsp-prod",
                                                                "tenantId": "tsp-prod",
                                                                "vin": "VIN-REACT-001",
                                                                "thread.id": "38"
                                                            },
                                                            "inner_domain_id": 10936,
                                                            "biz_id": 6611906,
                                                            "app_id": 3335513,
                                                            "env_id": 2311242,
                                                            "instance_id": 99804,
                                                            "time_used": 13,
                                                            "env_name": "test",
                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                            "app_name": "tsp-trace-service1",
                                                            "region": "cn-east-3",
                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                            "ip_address": "undef-ip",
                                                            "print_trace_id_flag": false,
                                                            "app_type": "JAVA",
                                                            "children": [
                                                                {
                                                                    "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                                    "span_id": "0ed6ab0785e74441",
                                                                    "parent_spanId": "46d192dff90af8d4",
                                                                    "start_time": 1774505652190,
                                                                    "operation_name": "Session.merge com.tsp.service1.entity.CommandRecord",
                                                                    "span_type": "SPAN_KIND_INTERNAL",
                                                                    "tags": {
                                                                        "baggage.userId": "user-001",
                                                                        "otel.scope.name": "io.opentelemetry.hibernate-4.0",
                                                                        "baggage.platform": "h5",
                                                                        "baggage.tenantId": "tsp-prod",
                                                                        "tenantId": "tsp-prod",
                                                                        "vin": "VIN-REACT-001",
                                                                        "baggage.vin": "VIN-REACT-001",
                                                                        "otel.scope.version": "2.25.0-alpha",
                                                                        "thread.name": "http-nio-8091-exec-10",
                                                                        "userId": "user-001",
                                                                        "platform": "h5",
                                                                        "thread.id": "38"
                                                                    },
                                                                    "inner_domain_id": 10936,
                                                                    "biz_id": 6611906,
                                                                    "app_id": 3335513,
                                                                    "env_id": 2311242,
                                                                    "instance_id": 99804,
                                                                    "time_used": 0,
                                                                    "env_name": "test",
                                                                    "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                                    "app_name": "tsp-trace-service1",
                                                                    "region": "cn-east-3",
                                                                    "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                                    "ip_address": "undef-ip",
                                                                    "print_trace_id_flag": false,
                                                                    "app_type": "JAVA"
                                                                },
                                                                {
                                                                    "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                                    "span_id": "e5e146224d8b0528",
                                                                    "parent_spanId": "46d192dff90af8d4",
                                                                    "start_time": 1774505652191,
                                                                    "operation_name": "Transaction.commit",
                                                                    "span_type": "SPAN_KIND_INTERNAL",
                                                                    "tags": {
                                                                        "baggage.userId": "user-001",
                                                                        "otel.scope.name": "io.opentelemetry.hibernate-4.0",
                                                                        "baggage.platform": "h5",
                                                                        "baggage.tenantId": "tsp-prod",
                                                                        "tenantId": "tsp-prod",
                                                                        "vin": "VIN-REACT-001",
                                                                        "baggage.vin": "VIN-REACT-001",
                                                                        "otel.scope.version": "2.25.0-alpha",
                                                                        "thread.name": "http-nio-8091-exec-10",
                                                                        "userId": "user-001",
                                                                        "platform": "h5",
                                                                        "thread.id": "38"
                                                                    },
                                                                    "inner_domain_id": 10936,
                                                                    "biz_id": 6611906,
                                                                    "app_id": 3335513,
                                                                    "env_id": 2311242,
                                                                    "instance_id": 99804,
                                                                    "time_used": 11,
                                                                    "env_name": "test",
                                                                    "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                                    "app_name": "tsp-trace-service1",
                                                                    "region": "cn-east-3",
                                                                    "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                                    "ip_address": "undef-ip",
                                                                    "print_trace_id_flag": false,
                                                                    "app_type": "JAVA",
                                                                    "children": [
                                                                        {
                                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                                            "span_id": "04dde408112f3ed4",
                                                                            "parent_spanId": "e5e146224d8b0528",
                                                                            "start_time": 1774505652192,
                                                                            "operation_name": "update s1_command_record set call_type=?, command_type=?, created_at=?, span_id=?, status=?, trace_id=?, vin=? where id=?",
                                                                            "span_type": "SPAN_KIND_CLIENT",
                                                                            "tags": {
                                                                                "db.connection_string": "mysql://172.19.64.30:13306",
                                                                                "otel.scope.name": "io.opentelemetry.jdbc",
                                                                                "db.statement": "update s1_command_record set call_type=?, command_type=?, created_at=?, span_id=?, status=?, trace_id=?, vin=? where id=?",
                                                                                "baggage.platform": "h5",
                                                                                "db.sql.table": "s1_command_record",
                                                                                "db.operation": "UPDATE",
                                                                                "baggage.vin": "VIN-REACT-001",
                                                                                "otel.scope.version": "2.25.0-alpha",
                                                                                "thread.name": "http-nio-8091-exec-10",
                                                                                "userId": "user-001",
                                                                                "platform": "h5",
                                                                                "server.address": "172.19.64.30",
                                                                                "db.user": "chery-alert",
                                                                                "baggage.userId": "user-001",
                                                                                "db.system": "mysql",
                                                                                "peer.service": "MySQL",
                                                                                "baggage.tenantId": "tsp-prod",
                                                                                "tenantId": "tsp-prod",
                                                                                "server.port": "13306",
                                                                                "vin": "VIN-REACT-001",
                                                                                "db.name": "trace_demo",
                                                                                "thread.id": "38"
                                                                            },
                                                                            "inner_domain_id": 10936,
                                                                            "biz_id": 6611906,
                                                                            "app_id": 3335513,
                                                                            "env_id": 2311242,
                                                                            "instance_id": 99804,
                                                                            "time_used": 1,
                                                                            "env_name": "test",
                                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                                            "app_name": "tsp-trace-service1",
                                                                            "region": "cn-east-3",
                                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                                            "ip_address": "undef-ip",
                                                                            "print_trace_id_flag": false,
                                                                            "app_type": "JAVA"
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            "trace_id": "d38b2c0d718a9efb81f0c1677f981a6b",
                                                            "span_id": "3a284c059642a403",
                                                            "parent_spanId": "09baf8a0bb37660e",
                                                            "start_time": 1774505652203,
                                                            "operation_name": "SETEX tsp:status:d38b2c0d718a9efb81f0c1677f981a6b 600 ?",
                                                            "span_type": "SPAN_KIND_CLIENT",
                                                            "tags": {
                                                                "otel.scope.name": "io.opentelemetry.lettuce-5.1",
                                                                "db.statement": "SETEX tsp:status:d38b2c0d718a9efb81f0c1677f981a6b 600 ?",
                                                                "baggage.platform": "h5",
                                                                "network.peer.port": "6379",
                                                                "baggage.vin": "VIN-REACT-001",
                                                                "otel.scope.version": "2.25.0-alpha",
                                                                "thread.name": "lettuce-nioEventLoop-4-1",
                                                                "userId": "user-001",
                                                                "platform": "h5",
                                                                "server.address": "172.19.64.30",
                                                                "network.peer.address": "172.19.64.30",
                                                                "baggage.userId": "user-001",
                                                                "db.system": "redis",
                                                                "peer.service": "Redis",
                                                                "baggage.tenantId": "tsp-prod",
                                                                "tenantId": "tsp-prod",
                                                                "server.port": "6379",
                                                                "vin": "VIN-REACT-001",
                                                                "network.type": "ipv4",
                                                                "thread.id": "42",
                                                                "db.connection_string": "redis://172.19.64.30:6379"
                                                            },
                                                            "inner_domain_id": 10936,
                                                            "biz_id": 6611906,
                                                            "app_id": 3335513,
                                                            "env_id": 2311242,
                                                            "instance_id": 99804,
                                                            "time_used": 1,
                                                            "env_name": "test",
                                                            "instance_name": "iZuf6f1jdvkslaq3jixzg2Z@undef-instancename@undef-ip(2eaecf80-389f-46f4-8b57-7bff559d7d53)",
                                                            "app_name": "tsp-trace-service1",
                                                            "region": "cn-east-3",
                                                            "host_name": "iZuf6f1jdvkslaq3jixzg2Z",
                                                            "ip_address": "undef-ip",
                                                            "print_trace_id_flag": false,
                                                            "app_type": "JAVA"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
  },
  "msg": "ok"
};
